// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csbwvuwwfmdumafhbymz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzYnd2dXd3Zm1kdW1hZmhieW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDQ2NjcsImV4cCI6MjA2OTcyMDY2N30.TogS3uDac2SJqlzysOHm3ulOU0T7Bkfr3yt9w5T_vDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});